baseURL: "https://data-consigliere.github.io/"
# Define a pasta de saída para o GitHub Pages
publishDir: "docs"

title: "DataConsigliere"
theme: "PaperMod"
languageCode: "en-us"

pagination:
  pagerSize: 10

params:
  # Configurações de Ativos (Essencial para GitHub Pages)
  assets:
    disableFingerprinting: true  # Evita que o CSS seja bloqueado por segurança (SRI)

  # Configurações do Tema
  profileMode:
    enabled: false
  homeInfoParams: {}

  # Mostrar footer do PaperMod (necessário para social icons)
  ShowFooter: true

  # Redes Sociais
  socialIcons:
    - name: github
      url: "https://github.com/JoseBagina"
    - name: linkedin
      url: "https://www.linkedin.com/in/josebagina/"
    - name: email
      url: "mailto:data.consigliere@proton.me"

# Configurações de Renderização
markup:
  goldmark:
    renderer:
      unsafe: true # Permite HTML dentro do Markdown

taxonomies:
  tag: "tags"
  category: "categories"

permalinks:
  posts: "/posts/:slug/"